---
- name: "DAAN DevOps Laptop Setup Script"
  hosts: localhost
  sudo: true
  roles:
    - role: geerlingguy.nodejs
    - role: geerlingguy.docker
    - role: brentwg.azure-cli
    - role: ngetchell.vscode
    - role: andrewrothstein.terraform
    - role: andrewrothstein.anaconda
  tasks:
    - name: Install Gnome Tweaks fix right-click issue
      apt: 
        name: gnome-tweaks
        state: present
  vars:
    - nodejs_version: "10.x" #latest LTS version of Nodejs
    - nodejs_npm_global_packages:
      - name: "@vue/cli"
